import React from "react";
import Head from "next/head";
import Header from "./Header";

const Landing = ({ nativeBalance, collections, setSelected, setSN }) => {
  return (
    <>
      <Head>
        <title>NFT Collections</title>
        <meta name="description" content="Generated by NFT Mint Page" />
        <link rel="icon" href="https://i.ibb.co/hWCgPFW/logo.png" />
      </Head>
      <main className="mint_page_wrapper">
        <Header nativeBalance={nativeBalance} setSelected={setSelected} />
        <div className="nft_collections">
          {collections?.map((c) => (
            <div
              onClick={() => {
                setSN(c?._id);
                setSelected("mint");
              }}
              key={c?._id}
              className="nft_collection"
            >
              <img
                id="collection_image"
                src={c?.previewImage}
                alt="nft collection"
                title="Non Fungible Token"
              />
              <h3>{c.title}</h3>
              <p>{c.description}</p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Landing;
